name: Zephyr CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-tk \
          xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
        pip3 install west

    - name: Install Zephyr and Python dependencies
      run: |
        west init ~/zephyrproject
        cd ~/zephyrproject
        west update
        west zephyr-export
        west packages pip --install
        cd zephyr
        west sdk install

    - name: Build for nucleo_f767zi
      run: |
        cd ~/zephyrproject
        west build zephyr-test-app -b nucleo_f767zi -p

    - name: Format check
      run: |
        cp zephyr/.clang-format .
        find . -name '*.[ch]' | xargs clang-format --dry-run --Werror

